socialpoint/socialpoint/urls.py
"""
socialpoint URL Configuration

The `urlpatterns` list routes URLs to views.
"""

from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from ImageProcessorApp.views import TaskDetailView, indexView, playTask,downloadImage


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^media/(?P<path>.*$)','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    # Url destinated to show the media files(images in our case)
    url(r'^task/(?P<slug>[-\w]+)/$',TaskDetailView.as_view()),
    # Details about a Task
    url(r'^play.*$', playTask, name='playTask'),
    # Launch  a task
    url(r'^download.*$', downloadImage, name='downloadImage'),
    # Download the images with a id passed
    url(r'^$',indexView, name='indexView'),
    # Upload the image and create a new task with it.

]

socialpoint/ImageProcessorApp/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.db import models


# Create your models here.

IMAGE_STATUS=[(1,"uploaded"),(2,"processing..."),(3,"finished")]
"""Task status that it can be"""

class Task(models.Model):
    """
    Entity that cointain all the information about image process.
    One Task by image
    :cvar name: Name asigned to task by user
    :cvar status: Image status(Uploaded,processing,finished)
    :cvar image: Uploaded image  by user
    :cvar image_converted: When image is converted is saved here
    :cvar uploaded: Date when the user has uploaded the image
    :cvar last_change: Date when the image state has changed last time
    :cvar slug: idetify to localize by url the task.Format: "name-id"
    """
    name =  models.CharField(max_length = 200)
    status = models.IntegerField(choices = IMAGE_STATUS, default = 1)
    image = models.ImageField()
    image_converted = models.ImageField()
    uploaded = models.DateTimeField(auto_now_add = True)
    last_change = models.DateTimeField(auto_now_add = True)
    slug = models.SlugField(editable = False,unique=True)


    class Meta:
        """
        Information about Task to manage the model
        To be more efficient, i order by upload date.
        """
        db_table = 'tasks'
        ordering = ['-uploaded']
        verbose_name_plural = 'tasks'

    def __unicode__(self):
        return self.name

    def save(self,*args,**kwargs):
        """
        Save Task instance adding a slug based in name and id.
        """
        if not self.id:
            super(Task,self).save(*args,**kwargs)
            self.slug = slugify(self.name) + "-" + str(self.id)
        super(Task,self).save(*args,**kwargs)

socialpoint/ImageProcessorApp/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    """
    ModelForm based Task. It's used to upload the image and create the task
    """
    class Meta:
        model = Task
        fields = ('name', 'image',)

socialpoint/ImageProcessorApp/views.py
"""
All views in proyect
"""

from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.edit import FormView
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.utils.timezone import now
from django.utils.encoding import smart_str
from celery.task.control import inspect
import json
from .models import Task
from .forms import TaskForm
from .task import *

class TaskDetailView(DetailView):
    """
    This view contain all the iformation about a particular Task
    """
    template_name = 'task.html'
    model = Task

def indexView(request):
    """
    This is the index, to list all the Task grouped by status and to show the form
    to upload new tasks. So
        * With GET response this list with empty form
        * With POST from Task form, test if form is valid, save the task and refresh
            if it's not valid, return the error.
    """
    tasks  = Task.objects.order_by('status')
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST,request.FILES) # Bound form
        if form.is_valid():
            new_task = form.save() # Guardar los datos en la base de datos
            return HttpResponseRedirect('/')
    else:
        form = TaskForm() # Unbound form
    return render(request, 'index.html', {'form': form, 'object_list':tasks})

def playTask(request):
    """
    This view Receive GET request by AJAX with the id to request start.
    This view test if there are more than 3 task in execution and return a json
        with the task result.
    """
    idTask = request.GET['id']
    task = Task.objects.get(id=idTask)

    if Task.objects.filter(status=2).count() < 3 :
        task.status = 2
        task.last_change = now()
        task.save()
        setFormatImage.apply_async((task.pk,),countdown=10)

    resp = {'status': task.status, 'id':task.id}
    return JsonResponse(resp)

def downloadImage(request):
    """
    This view manage download requests to response with the image requested
    """
    #Search task
    idTask = request.GET['id']
    task = Task.objects.get(id=idTask)
    file_name= task.image_converted.name
    path_to_file = task.image_converted.file

    #response
    response = HttpResponse(content_type="image/jpeg")
    img = Image.open(path_to_file)
    img.save(response,'jpeg')
    response['Content-Disposition'] = 'attachment; filename="'+ str(file_name) +'"'
    return response

socialpoint/ImageProcessorApp/templates/AddTask.html
{% extends 'esqueleton.html' %}

{% block content %}
<form action="{% url 'indexView' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Add Task </button>
</form>
{% endblock %}

socialpoint/ImageProcessorApp/templates/esqueleton.html
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

</head>
<body>
    <div class="content container">
        <div class="row">
            <div class="col-md-12">
            {% block content %}

            {% endblock %}
            </div>
        </div>
        </div>
    </div>

<script>
    /*
    This script is here because i was having problems with \{%static%\}.
    In static directory it's the same but in js file
    */
    /* Class to extract GET parameters from URL*/
    Url = {
        get(){
            var vars= {};
            if(window.location.search.length!==0)
                window.location.search.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value){
                    key=decodeURIComponent(key);
                    if(typeof vars[key]==="undefined") {vars[key]= decodeURIComponent(value);}
                    else {vars[key]= [].concat(vars[key], decodeURIComponent(value));}
                });
            return vars;
        }
    };

    $(document).ready(function(){
        //Show errors
        if(Url.get('error').error == 'exceded'){
            $('#error').append('<em>Error:</em> 3 works in progress! Wait...')
            $('#error').show()
        }
        //Send by AJAX the order to execute a task (for after do the autosync)
        $(".btn-play").click(function(){
            $.get( "play", { id: $(this).attr('id') },function(data){
                //If server response with a task state diferent of processing, jump error
                if(data['status'] != "2"){
                    window.location.href="/?error=exceded";
                }else window.location.href="/";
            } );
        });
    });
</script>
</body>

socialpoint/ImageProcessorApp/templates/index.html
{% extends 'esqueleton.html' %}

{% block content %}

<body>
    <h1>Tareas</h1>
    <!-- PANEL INFO AND BUTTONS -->
        <button id="refresh" class="btn btn-default" onclick='window.location.href="/"'>Refresh</button></br>
        <br><div id="error" class="alert alert-danger alert-dismissible" role="alert" hidden="hidden"></div>
        <br><p>Estimated time: 10 second</p>
    <!-- end PANEL INFO AND BUTTONS -->
    <!-- TASK REGROUPED BY STATUS -->
                {% regroup object_list by get_status_display as task_list %}

                    {% for task in task_list %}
                    <table class="table table-striped">
                        <thead class="center">
                            <tr><h3>{{ task.grouper }}</h3></tr>
                        <tr>
                            <th>Nombre</th>
                            <th>Uploaded</th>
                            <th>Last Change</th>
                            <th>Status</th>
                            <th>Uploaded Image</th>
                            <th></th>
                        <tr>
                        <thead>
                        <tbody>
                            {% for item in task.list %}
                            <tr id="{{ item.id }}" class="task-table">
                                <td id="name-{{ item.id }}" name="name"> <a href="/task/{{ item.slug }}/"> {{ item.name }} </a> </td>
                                <td name="uploaded"> {{ item.uploaded }} </td>
                                <td name="last_change"> {{ item.last_change }} </td>
                                <td name="status"> {{ item.get_status_display }} </td>
                                <td name="image"><a href="{{item.image.url}}"> {{ item.image.name }} </a></td>
                                <td><button id="{{ item.id }}" class="btn-play btn btn-success" >Play</button><td>
                                {% if item.status == 3 %}
                                    <td><button id="{{ item.id }}" class="btn-download btn btn-warning" onclick='window.location.href="download?id={{ item.id }}"'>Download</button><td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                    {% endfor %}
        </tbody>
    </table>
<!-- TASK REGROUPED BY STATUS -->
<!-- UPLOAD TASK PANEL -->
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="{% url 'indexView' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                <p> <em>To identify the task, you have to into a name</em></p>
                {{ form.as_p }}
                <button type="submit" class="btn btn-info"> Add Task </button>
            </form>
        </div>
    </div>
<!-- end UPLOAD TASK PANEL -->
</body>

{% endblock %}

socialpoint/ImageProcessorApp/templates/task.html
{% extends 'esqueleton.html' %}

{% block content %}
<!-- TASK INFO -->
<div class="panel panel-default">
    <div class="panel-head">
        <h1> {{ object.name }} </h1>
    </div>
        <div class="panel-body">
        <table class="table table-striped">
            <thead class="center">
            <tr>
                <th>Status</th>
                <th>Uploaded Date</th>
                <th>Last Change</th>
                <th>Image</th>
            <tr>
            <thead>
            <tbody>
            <tr>
                <td> {{ object.get_status_display }} </td>
                <td> {{ object.uploaded }} </td>
                <td> {{ object.last_change }}</td>
                <td> {{ object.image }}
            </tr>
            <tbody>

        </table>
        <div class="col-md 12">
            <img width="100%" src="{{ object.image.url }}">
        </div>
    </div>
</div>
<!-- end TASK INFO -->

{% endblock %}